# Generated by Django 5.2.7 on 2025-10-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('sentiment_label', models.CharField(max_length=10, null=True)),
                ('sentiment_score', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mainuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sfas_app.mainuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
